<!DOCTYPE html>
<html lang="en" class="scrollbar-custom text-[14px] sm:text-[16px] 2xl:text-[20px]">
<!-- HEAD -->

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | SiMELEK</title>
    <!-- Base CSS (generated by Tailwind) -->
    <link rel="stylesheet" href="<?= base_url('/assets/css/base.css') ?>">
    <!-- Custom Fonts CSS -->
    <link rel="stylesheet" href="<?= base_url('/assets/css/fonts.css') ?>">
</head>
<!-- Akhir HEAD -->

<body class="grid grid-cols-1 lg:grid-cols-12">
    <!-- Aside -->
    <aside class="fixed lg:sticky top-0 translate-x-[-100%] lg:translate-x-0 w-screen lg:w-full lg:col-span-3 xl:col-span-2 border-r border-solid border-gray-200 z-[9999999]">
        <!-- hidden opacity-0 invisible -->
        <div class="nav-overlay lg:hidden absolute top-0 left-0 w-screen h-screen bg-black/35 z-[-1]"></div>
        <!-- Navigation Container -->
        <div class="nav-container scrollbar-custom relative lg:w-full w-fit h-screen bg-white z-10 overflow-y-auto">
            <!-- Top/Legend Navigation -->
            <div class="top-nav pt-6 pb-4 px-6 flex gap-4 tracking-wider">
                <div class="title">
                    <h2 class="text-xl text-green">SiMELEK</h2>
                    <p class="mt-0.5 text-xs text-gray-500/90 text-pretty">Sistem Informasi Media Elektronik</p>
                </div>
                <button type="button" class="lg:hidden">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
            <div class="profiles py-4 px-2.5 flex gap-3 border-y border-solid border-gray-200 bg-blue-100">
                <figure class="shrink-0 p-0.5 bg-white rounded-full overflow-hidden">
                    <img src="https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2281862025.jpg" alt="Profil <nama_user>" class="size-11" />
                </figure>
                <div class="text-xs flex-1 min-w-0 flex flex-col justify-center gap-0.5">
                    <p class="truncate text-sm font-semibold">fattahillah</p>
                    <p class="text-xs text-gray-500/90"><?= $role ?></p>
                </div>
            </div>
            <nav class="scrollbar-custom p-4 flex flex-col gap-2 min-h-[230px] max-h-[230px] overflow-y-auto border-b border-solid border-gray-200">
                <a href="<?= $navigation === 'Dashboard' ? 'javascript:void(0)' : '/dashboard' ?>" class="beranda font-text text-sm p-3 flex items-center font-semibold gap-1.5 rounded-lg <?= $navigation === 'Dashboard' ? 'bg-blue-600 text-white' : 'text-gray-500/90 transition duration-150 ease-in hover:bg-gray-200 focus:outline-none focus:bg-gray-200' ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                    </svg>
                    <span class="truncate" title="Dashboard">Dashboard</span>
                </a>

                <a href="<?= $navigation === 'Pengajuan' ? 'javascript:void(0)' : '/dashboard/pengajuan' ?>" class="pengajuan font-text text-sm p-3 flex items-center font-semibold gap-1.5 rounded-lg <?= $navigation === 'Pengajuan' ? 'bg-blue-600 text-white' : 'text-gray-500/90 transition duration-150 ease-in hover:bg-gray-200 focus:outline-none focus:bg-gray-200' ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 9.776c.112-.017.227-.026.344-.026h15.812c.117 0 .232.009.344.026m-16.5 0a2.25 2.25 0 0 0-1.883 2.542l.857 6a2.25 2.25 0 0 0 2.227 1.932H19.05a2.25 2.25 0 0 0 2.227-1.932l.857-6a2.25 2.25 0 0 0-1.883-2.542m-16.5 0V6A2.25 2.25 0 0 1 6 3.75h3.879a1.5 1.5 0 0 1 1.06.44l2.122 2.12a1.5 1.5 0 0 0 1.06.44H18A2.25 2.25 0 0 1 20.25 9v.776" />
                    </svg>
                    <span class="truncate" title="Pengajuan">Pengajuan</span>
                </a>

                <a href="<?= $navigation === 'Riwayat Pengajuan' ? 'javascript:void(0)' : '/dashboard/riwayat-pengajuan' ?>" class="riwayat-pengajuan font-text text-sm p-3 flex items-center font-semibold gap-1.5 rounded-lg <?= $navigation === 'Riwayat Pengajuan' ? 'bg-blue-600 text-white' : 'text-gray-500/90 transition duration-150 ease-in hover:bg-gray-200 focus:outline-none focus:bg-gray-200' ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m7.875 14.25 1.214 1.942a2.25 2.25 0 0 0 1.908 1.058h2.006c.776 0 1.497-.4 1.908-1.058l1.214-1.942M2.41 9h4.636a2.25 2.25 0 0 1 1.872 1.002l.164.246a2.25 2.25 0 0 0 1.872 1.002h2.092a2.25 2.25 0 0 0 1.872-1.002l.164-.246A2.25 2.25 0 0 1 16.954 9h4.636M2.41 9a2.25 2.25 0 0 0-.16.832V12a2.25 2.25 0 0 0 2.25 2.25h15A2.25 2.25 0 0 0 21.75 12V9.832c0-.287-.055-.57-.16-.832M2.41 9a2.25 2.25 0 0 1 .382-.632l3.285-3.832a2.25 2.25 0 0 1 1.708-.786h8.43c.657 0 1.281.287 1.709.786l3.284 3.832c.163.19.291.404.382.632M4.5 20.25h15A2.25 2.25 0 0 0 21.75 18v-2.625c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125V18a2.25 2.25 0 0 0 2.25 2.25Z" />
                    </svg>
                    <span class="truncate" title="Riwayat Pengajuan">Riwayat Pengajuan</span>
                </a>

                <a href="<?= $navigation === 'Riwayat Hapus' ? 'javascript:void(0)' : '/dashboard/riwayat-hapus' ?>" class="riwayat-hapus font-text text-sm p-3 flex items-center font-semibold gap-1.5 rounded-lg <?= $navigation === 'Riwayat Hapus' ? 'bg-blue-600 text-white' : 'text-gray-500/90 transition duration-150 ease-in hover:bg-gray-200 focus:outline-none focus:bg-gray-200' ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                    </svg>
                    <span class="truncate" title="Riwayat Hapus">Riwayat Hapus</span>
                </a>
            </nav>
            <!-- Mores Navigation -->
            <div class="mores-nav p-4 flex flex-col gap-2">
                <!-- Navigasi Pengaturan -->
                <div class="setting-group">
                    <span class="pengaturan font-text p-3 flex items-center gap-1.5 text-gray-500/90 rounded-lg transition duration-150 ease-in hover:bg-gray-200 focus:outline-none focus:bg-gray-200 cursor-pointer" role="button">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 0 1 1.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.559.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.894.149c-.424.07-.764.383-.929.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 0 1-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.398.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 0 1-.12-1.45l.527-.737c.25-.35.272-.806.108-1.204-.165-.397-.506-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.108-1.204l-.526-.738a1.125 1.125 0 0 1 .12-1.45l.773-.773a1.125 1.125 0 0 1 1.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894Z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                        </svg>
                        <span class="font-semibold truncate text-sm" title="Pengaturan">Pengaturan</span>
                    </span>
                    <!-- Navigasi Dropdown Pengaturan -->
                    <!--
                        @note: tambahkan animasi pada dropdown saat tombolnya diklik
                            - berikan properti max-height
                    -->
                    <div class="settings-dropdown bg-white pl-5 max-h-0 overflow-hidden transition-[max-height] duration-500 ease-in">
                        <a href="<?= $navigation === 'Riwayat Hapus' ? 'javascript:void(0)' : '/dashboard/riwayat-hapus' ?>" class="riwayat-hapus font-text text-sm p-3 flex items-center font-semibold gap-1.5 rounded-lg <?= $navigation === 'Riwayat Hapus' ? 'bg-blue-600 text-white' : 'text-gray-500/90 transition duration-150 ease-in hover:bg-gray-200 focus:outline-none focus:bg-gray-200' ?>">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                            </svg>
                            <span class="truncate" title="Profil">Profil</span>
                        </a>
                    </div>
                </div>
                <!-- Navigasi Log Out -->
                <a href="/dashboard/logout" class="logout active font-text p-3 flex items-center gap-1.5 text-red-500 rounded-lg transition duration-150 ease-in hover:bg-red-100 focus:outline-none focus:bg-red-100" aria-label="Keluar">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M5.636 5.636a9 9 0 1 0 12.728 0M12 3v9" />
                    </svg>
                    <span class="font-semibold truncate text-sm" title="Pengaturan">Keluar</span>
                </a>
            </div>
        </div>
    </aside>
    <!-- Akhir Aside -->
    <!-- Main -->
    <main class="flex flex-col h-screen lg:col-span-9 xl:col-span-10 bg-primary overflow-hidden">
        <!-- Header -->
        <header class="shrink-0 sticky top-0 py-8 md:py-5 px-7 flex items-center justify-between gap-6 sm:gap-0 bg-white border-b border-solid border-gray-200 shadow-sm z-10">
            <!-- Header left -->
            <aside class="start-header flex items-center gap-4 lg:gap-0">
                <!-- Hamburber menu, for viewport width < 1024px -->
                <button type="button" class="hamburger lg:hidden py-1 px-2 shrink-0 border-[1.5px] border-solid border-gray-200 rounded transition duration-150 hover:bg-gray-100" aria-label="Buka notifikasi">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                </button>
                <!-- Greets text -->
                <div class="greets">
                    <h1 class="text-xl"><?= $navigation ?></h1>
                    <span class="font-text text-sm text-gray-500/90"><?= $subtitle ?></span>
                </div>
            </aside>
            <!-- Akhir Header left -->
            <!-- Aside Header -->
            <aside class="flex items-center gap-5">
                <!-- Notification Wrapper -->
                <div class="notification-wrapper relative">
                    <!-- Button show Notification -->
                    <button type="button" class="relative py-1.5 px-2 h-fit border-[1.5px] border-solid border-gray-200 rounded-md transition duration-150 hover:bg-gray-100 focus:outline-gray-200 focus:bg-gray-100">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 sm:size-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
                        </svg>
                        <span class="font-text absolute -top-1.5 -right-2.5 py-0.5 px-1.5 bg-red-500 text-[.75rem] text-white rounded-full">2</span>
                    </button>
                    <!-- Notifications Message -->
                    <div class="notifications hidden absolute top-16 sm:top-13 md:top-11 lg:top-14 xl:top-11 right-0 bg-white border border-solid border-gray-200 shadow-md rounded-lg overflow-hidden">
                        <!-- Notification Legend -->
                        <div class="notification-legend p-4 w-96 flex flex-col border-b border-solid border-gray-200">
                            <h2 class="text-lg">Notifikasi</h2>
                            <p class="text-xs text-gray-500/90 tracking-wider">2 notifikasi belum dibaca</p>
                        </div>
                        <!-- Notification message info -->
                        <div class="notification-message scrollbar-custom min-h-96 max-h-96 2xl:min-h-[65vh] 2xl:max-h-[65vh] flex flex-col overflow-y-auto">
                            <a href="#" class="py-3.5 px-4 flex gap-2.5 bg-blue-50/95 border-b border-solid border-gray-200 transition duration-150 hover:bg-primary">
                                <span class="mt-0.5 text-green-600">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                    </svg>
                                </span>
                                <div class="notification-info flex flex-col gap-0.5">
                                    <h3 class="flex justify-between items-center text-sm">Pengajuan disetujui<span class="inline-block mr-2 w-2 h-2 bg-blue-500 rounded-full"></span></h3>
                                    <p class="mt-0.5 text-sm text-gray-500/90">Pengajuan "Liputan Pemilu 2026" Anda telah disetujui Admin</p>
                                    <span class="mt-1 flex gap-1 text-gray-500/90 text-xs">5 hari yang lalu</span>
                                </div>
                            </a>
                            <a href="#" class="py-3.5 px-4 flex gap-2.5 bg-blue-50/95 border-b border-solid border-gray-200 transition duration-150 hover:bg-primary">
                                <span class="mt-0.5 text-red-600">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                    </svg>
                                </span>
                                <div class="notification-info flex flex-col gap-0.5">
                                    <h3 class="flex justify-between items-center text-sm">Pengajuan ditolak<span class="inline-block mr-2 w-2 h-2 bg-blue-500 rounded-full"></span></h3>
                                    <p class="mt-0.5 text-sm text-gray-500/90">Pengajuan "Festival Budaya Nusantara" Anda telah ditolak Admin. Lihat alasan penolakan di Pengajuan anda</p>
                                    <span class="mt-1 flex gap-1 text-gray-500/90 text-xs">7 hari yang lalu</span>
                                </div>
                            </a>
                            <a href="#" class="py-3.5 px-4 flex gap-2.5 bg-white border-b border-solid border-gray-200 transition duration-150 hover:bg-primary">
                                <span class="mt-0.5 text-amber-600">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                    </svg>
                                </span>
                                <div class="notification-info flex flex-col gap-0.5">
                                    <h3 class="flex justify-between items-center text-sm">Pengajuan terkirim</h3>
                                    <p class="mt-0.5 text-sm text-gray-500/90">Pengajuan "Investigasi Korupsi Daerah" Anda telah terkirim, mohon tunggu persetujuan dari Admin</p>
                                    <span class="mt-1 flex gap-1 text-gray-500/90 text-xs">8 hari yang lalu</span>
                                </div>
                            </a>
                            <a href="#" class="py-3.5 px-4 flex gap-2.5 bg-white border-b border-solid border-gray-200 transition duration-150 hover:bg-primary">
                                <span class="mt-0.5 text-indigo-600">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                                    </svg>
                                </span>
                                <div class="notification-info flex flex-col gap-0.5">
                                    <h3 class="flex justify-between items-center text-sm">Perbaikan pengajuan</h3>
                                    <p class="mt-0.5 text-sm text-gray-500/90">Pengajuan "Dewan Dorong Pemda dan APH Perkuat Pengawasan PETI" Anda butuh perbaikan. Lihat komentar Admin tentang perbaikan!</p>
                                    <span class="mt-1 flex gap-1 text-gray-500/90 text-xs">9 hari yang lalu</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- Header link Pengajuan -->
                <?php if ($navigation !== 'Pengajuan'): ?>
                    <a href="/dashboard/pengajuan" class="hidden lg:flex py-2 px-2.5 gap-1 bg-blue-500 text-white rounded-md transition duration-150 hover:bg-blue-600 focus:outline-none focus:bg-blue-600" aria-label="Buat pengajuan baru">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>
                        <span class="font-semibold font-text text-sm">Pengajuan Baru</span>
                    </a>
                <?php endif ?>
            </aside>
            <!-- Akhir Aside Header -->
        </header>
        <!-- Akhir Header -->
        <!-- Content -->
        <div class="scrollbar-custom content-container h-full overflow-y-auto">
            <div class="content py-6 px-6 md:py-8 sm:px-10 flex flex-col gap-6">
                <?= $this->renderSection('content') ?>
            </div>
        </div>
        <!-- Akhir Content -->
    </main>
    <!-- Akhir Main -->
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="<?= base_url('/assets/css/scrollbar-custom.css') ?>">
</body>

</html>